name: Test Install IDA Action

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  test-action:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - { os: ubuntu-latest,  platform: linux,   installer_id: "release/9.1/ida-pro/ida-pro_91_x64linux.run" }
          - { os: windows-latest, platform: windows, installer_id: "release/9.1/ida-pro/ida-pro_91_x64win.exe" }
          - { os: macos-latest,   platform: macos,   installer_id: "release/9.1/ida-pro/ida-pro_91_armmac.app.zip" }
      fail-fast: false

    name: Test IDA 9.1 on ${{ matrix.platform }}

    steps:
    - name: Checkout action code
      uses: actions/checkout@v4

    # Test your local action using relative path
    - name: Test Install IDA Pro Action
      uses: ./install-ida  # This runs the action.yml in the install-ida directory
      with:
        installer-id: ${{ matrix.installer_id }}
        license-id: ${{ secrets.IDA_LICENSE_ID }}
        api-key: ${{ secrets.HCLI_API_KEY }}

    # Verify the installation worked
    - name: Verify Installation
      shell: bash
      run: |
        echo "Checking IDADIR environment variable..."
        echo "IDADIR: $IDADIR"
        echo "IDABIN: $IDABIN"
        
        echo "Checking if IDA directory exists..."
        if [ -d "$IDADIR" ]; then
          echo "IDA directory exists at: $IDADIR"
          echo "Contents:"
          ls -la "$IDADIR"
        else
          echo "IDA directory not found at: $IDADIR"
          exit 1
        fi
        
        echo "Checking if IDA binary exists..."
        if [ -f "$IDABIN" ] || [ -f "$IDABIN.exe" ]; then
          echo "IDA binary found at: $IDABIN"
        else
          echo "IDA binary not found at: $IDABIN"
          exit 1
        fi

    # Test basic IDA functionality by checking version (if tools not cleaned)
    - name: Test basic IDA functionality
      shell: bash
      run: |
        echo "Testing basic IDA setup..."
        echo "IDADIR is set to: $IDADIR"
        echo "IDABIN is set to: $IDABIN"
        
        # Try to get IDA version (works on all platforms)
        if [ -f "$IDABIN" ]; then
          echo "Testing IDA binary..."
          # Most IDA versions support --version or similar
          "$IDABIN" --help || echo "IDA binary exists but help not available"
        elif [ -f "$IDABIN.exe" ]; then
          echo "Testing IDA binary (Windows)..."
          "$IDABIN.exe" --help || echo "IDA binary exists but help not available"
        else
          echo "IDA binary check - file exists verification passed earlier"
        fi